Import('RTT_ROOT')
Import('rtconfig')
from building import *

# change it if you want to use a different chip
llvm_target = 'thumbv7em-none-eabihf'

cargo = Builder(action = [
        'cargo build --manifest-path ${SOURCE.abspath} --target ${LLVM_TARGET}  --target-dir ${TARGET.dir.abspath}',
        Copy('${TARGET.abspath}', '${TARGET.dir.abspath}/${LLVM_TARGET}/debug/${TARGET.file}')
    ],
    suffix = '.a',
    src_suffix = '.toml',
    prefix = 'lib',
    chdir = 0)

Env.Append(BUILDERS = {'Cargo' : cargo})
#Env.AppendUnique(LLVM_TARGET = llvm_target)

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd, ]

# 'rustapp' is ".a" file name
rustapp = Env.Cargo('rustapp', 'Cargo.toml')
Env.AlwaysBuild(rustapp)

group = DefineGroup('rustapp', src, depend = [''], LIBS = [rustapp], CPPPATH = CPPPATH, #LINKFLAGS = ' -z muldefs'
                    )

Return('group')
